### ISSUE TITLE
Sed always adds newline

### ISSUE THREAD

**Issue by ghost** [9fans/plan9port#172]
Expected behaviour:
`; printf test|sed ''`
`    test;`

What happens:
`; printf test|sed ''`
`test`
`; `

GNU/Sed works fine.

**Comment by dancrossnyc** [comment]
Hmm. I think there are good arguments for why the current behavior is correct; sed is fundamentally line-oriented and GNU sed is a rather different animal. This has been the historical behavior since the 1970s, and one can of course use GNU sed with plan9port tools if one really needs the "preserve no newline at EOF" behavior.

In this case, as much as we appreciate the report, I think that parity with plan9's behavior outweighs parity with Unix behavior, so I'm going to close the issue. If you disagree strongly, feel free to reopen.
