### ISSUE TITLE
libdraw string crash using display->white

### ISSUE THREAD

**Issue by majiru** [9fans/plan9port#244]
Not sure if this is intended behavior or not, but using `screen->white` for the `Image*` in the argument to `string()` from libdraw seems to cause a crash. It seems string is expecting some attributes that are not present in `display->white`. The crash itself is at `$PLAN9/src/libdraw/string.c:105` when it tries to grab the id of the `display->white` `Image*`. 

This seems to crash:
```
string(screen, screen->r.min, display->white, screen->r.min, font, "test");
```

Where as doing something like:
```
Image *white = allocimage(display, Rect(0, 0, 1, 1), RGB24, 1, DWhite);
string(screen, screen->r.min, white, screen->r.min, font, "test");
```

Seems to work just fine

**Comment by rsc** [comment]
It sounds like you have memory corruption.
The implication of that access crashing is that display->white == nil or is otherwise an invalid pointer (perhaps display itself was corrupted).
The setup for display is pretty clearly initializing display->white though:

	disp->image = image;
	disp->white = allocimage(disp, Rect(0, 0, 1, 1), GREY1, 1, DWhite);
	disp->black = allocimage(disp, Rect(0, 0, 1, 1), GREY1, 1, DBlack);
	if(disp->white == nil || disp->black == nil){
		free(disp->white);
		free(disp->black);
		goto Error4;
	}

Without a program to reproduce with, I'm going to close this. If you are still seeing it in a simple test program, please file a new issue with that test program.
