### ISSUE TITLE
Segfault on Font

### ISSUE THREAD

**Issue by blakemcbride** [9fans/plan9port#25]
I have fontsrv running.  Some of the fonts have spaces in them.  If I try to execute:

Font /mnt/font/Courier New/12a/font

I get a segfault.  But the following works as expected:

Font /mnt/font/Ubuntu/12a/font

Like elsewhere in acme, you can't have a space in a path.

**Comment by gleydsonsoares** [comment]
Seems that libdraw doesn't such the expected font...
try: acme -f '/mnt/font/Courier New/12a/font'

The segfault happens because libdraw doesn't check for a valid (Font *f) pointer. 

I already sent the patch to fix this issue, you can follow here:
https://plan9port-review.googlesource.com/#/c/1220/

**Comment by rsc** [comment]
The crash was fixed in 25822e8da338df2c15959bd8d347f230dc2b2d89 (long ago).
The restriction on having no spaces in font names persists, sorry.
If fontsrv still does that we should make it pull the spaces out of the names.
