### ISSUE TITLE
mouse cursor not auto move

### ISSUE THREAD

**Issue by itetao** [9fans/plan9port#294]
os: fedora30
cc: clang 8

may i have your help, very thanks
after INSTALL plan9port , everything is ok, but cannot auto move cursor when use mouse button 3 to search or file jump.

**Comment by mkhl** [comment]
This seems to happen when running Wayland instead of X. We should investigate whether Wayland (or maybe Xwayland) supports programmatically moving the cursor.

To work around this issue on Fedora, at the graphical login screen there's a gear icon next to the login button. Clicking it opens a menu where one can select between (if I remember correctly) Gnome, Gnome Classic, and Gnome on X. Selecting Gnome on X ensures the graphical session runs Xorg, and Acme supports moving the cursor there.

**Comment by itetao** [comment]
yes, i got it, it work good when i select gnome on xorg.  thanks very much
