### ISSUE TITLE
acme: Kcmd not being passed through on linux

### ISSUE THREAD

**Issue by andrewchambers** [9fans/plan9port#31]
Can't trigger copy or paste via keyboard with any combination of ctrl + alt + windows key.

From the code it looks like windows key is the correct combination.

When I add  `printf("key - %d\n", r);` @ https://github.com/9fans/plan9port/blob/3f1c876e14e7eb45c1e17e1f3f4a28d98ff9b35f/src/cmd/acme/text.c#L669 I get
key - 99 // When pressing c
key - 3   // When pressing Ctrl + c
key - 99 // When pressing Windows key + c
key - 99 // When pressing alt + c  (the keypress is sometimes ignored)

**Comment by mehlon** [comment]
[keyboard.h](https://github.com/9fans/plan9port/blob/master/include/keyboard.h#L42) says it's pretty much mac-only.
[This](https://github.com/mehlon/plan9port/commit/f834285f22db897b1a813148394494facbab3727) changes every occurence of Kcmd to a control sequence so you ctrl+c to copy. ([download as patch](https://github.com/mehlon/plan9port/commit/f834285f22db897b1a813148394494facbab3727.patch))

**Comment by andrewchambers** [comment]
How unfortunate that someone would accept mac only patches. Thanks mehlon.

**Comment by rsc** [comment]
We can't map Control to Kcmd because Kcmd+c (copy) and Ctrl+c (stop process) are very different operations. And Alt was taken too, for compose sequences. 

Now that just about everything has a Windows key too, if someone wants to map the Windows key to Kcmd, that would be fine. I don't know how though.
