### ISSUE TITLE
dformat is misattributed in the git log

### ISSUE THREAD

**Issue by arnoldrobbins** [9fans/plan9port#421]
The `dformat` program was written by Jon Bentley, but the git log (at least) attributes it to Brian Kernighan. This should be fixed if possible.

A full version of it can be found at https://github.com/arnoldrobbins/dformat.

**Comment by rsc** [comment]
Thanks. My guess is that wkj got it from bwk in 2004 (I believe they were both at Princeton at the time) and either didn't realize it was originally jlb's or simply meant to indicate where he got it from.

In any event, since it was checked into src/cmd/dformat, not bin/dformat, it wasn't in the usual $PATH and has likely never been used. Removed entirely.

The Git log can't be changed, but in the removal message I included a link to your copy. Thanks.
