### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by nmeum** [9fans/plan9port#47]
Previously it was possible to download tarballs from [google code](https://code.google.com/p/plan9port/downloads/list) these tarballs a slightly out of date nowadays, maybe it would be a good idea to use `git-tag(1)` to tag releases? When doing so GitHub automatically creates source tarballs for those git tags. This would make packaging plan9port easier.

**Comment by 0intro** [comment]
You can already download tarballs from any Git revision.

For example: https://github.com/9fans/plan9port/archive/6a93bd5c92.tar.gz

**Comment by nmeum** [comment]
Sure, but that's just an archive for everything that has been committed before the given commit, isn't it? Wouldn't it be better to mark certain revisions as 'stable' at some point, as in: tagging a release?

**Comment by rsc** [comment]
I consider the tree always stable. It doesn't change fast enough to get unstable. The old tarballs were generated before Google Code had the ability to download a source archive, so that packaging systems like FreeBSD ports could have a stable URL for a specific version of code. It seems to me that rather than do extra tagging, using the GitHub hash-based archive download service is fine.

**Comment by neonfuz** [comment]
It's disappointing to see this is the direction this project has decided to take. As a macos user, I now have to compile plan9port myself, and as a nixpkgs maintainer we have to mark any software which does not maintain tags as "unstable" despite how stable it is. I think plan9port should reconsider their decision. Especially considering updates are so infrequent, you could simply bump the version each release which changes the code, which would help package maintainers know when to update their packages, and allow it to be packaged in homebrew again.
