### ISSUE TITLE
Display glitches in acme

### ISSUE THREAD

**Issue by gnuvince** [9fans/plan9port#85]
Sometimes when using acme, some of the characters have display glitches; those glitches are intermitent (select the character and its displays fine), happen on Void Linux and Ubuntu 17.04, and happen with all the fonts I try (default font, Lucida Grande, Go, Go Mono, Inconsolata, etc.)

![2017-06-10-190927_749x228_scrot](https://user-images.githubusercontent.com/39868/27007066-c38901d0-4e13-11e7-8ffa-d97e706e062f.png)

**Comment by paulzhol** [comment]
@gnuvince do you see some output from acme(libdraw) itself?
Here's mine after inputting a non-ascii character:
`stringwidth: bad character set for rune 0x0000 in /mnt/font/Go Mono/12a/font`

**Comment by gnuvince** [comment]
@paulzhol nothing; here's another screenshot where the 'N' of 'New' in the global tag has rendering glitches.  I should mention that the same glitches happen in sam as well.

![2017-06-12-095158_561x179_scrot](https://user-images.githubusercontent.com/39868/27037107-f0d1a9c0-4f54-11e7-93c0-76ec77c91068.png)

**Comment by rsc** [comment]
There's definitely an incompatibility with Ubuntu on certain hardware. I have seen this myself but have no idea what causes it. I haven't been able to reproduce it with enough regularity to try to debug why it happens. Plan9port only uses non-fancy 2D graphics that most apps today don't exercise; maybe those code paths are rotting in the X server.

The relevant code is the function xdraw at the bottom of src/cmd/devdraw/x11-draw.c. You can change some of the if bodies to insert a 'return 0' at the beginning, instead of attempting acceleration. Honestly there aren't too many accelerated paths left, due to bugs like this. 

If you can figure out which path needs to be turned off, please let me know.

**Comment by rsc** [comment]
FWIW I went back to Ubuntu and I haven't been seeing this anymore. So I think they fixed their buggy X server maybe.
