### ISSUE TITLE
fontsrv courier

### ISSUE THREAD

**Issue by karisawa** [9fans/plan9port#86]
I love acme on retina mac book. my favourite font is courier bold.
However I cannot see any difference between `(back quote) and '(single quote) in courier.
is there fix of this problem.

**Comment by rsc** [comment]
You can change the code at $PLAN9/src/cmd/fontsrv/osx.c to not remap one or both of those characters to the "smart quote" equivalents. That is, the code says:

```
int
mapUnicode(int i)
{
        switch(i) {
        case '\'':
                return 0x2019;
        case '`':
                return 0x2018;
        }
        if(0xd800 <= i && i < 0xe0000) // surrogate pairs, will crash OS X libraries!
                return 0xfffd;
        return i;
}
```

and you can remove one case or the whole switch.

Normally that's the right behavior as implemented, since most fonts have easier to distinguish quote pairs, so I don't want to change it, but I certainly see what you mean about Courier-Bold. 

There really is a difference, but it's pretty subtle because both are angled the same way. The back quotes are wide at the bottom and the forward quotes are wide at the top:

<img width="287" alt="screen shot 2017-06-17 at 2 06 50 pm" src="https://user-images.githubusercontent.com/104030/27255149-3e74b66c-5366-11e7-84cd-a223fbcb7367.png">

**Comment by karisawa** [comment]
Thanks Russ,

That also fixed the problem with Osaka-Mono Font.
I love the font because it is designed for programming.
Many Japanese love the font for programming.
Hiragino and Osaka are two major fonts among Mac users in Japan.

Thanks again.

**Comment by rsc** [comment]
Thanks Kenji. Since there are two fonts, it sounds like probably there are more, so we should fix this more broadly. I added a list of fonts to fontsrv for which it does not apply the quote mapping. Currently that's any font for which there is a substring "Courier" or "Osaka".
